[workspace]
members = [
    ".",
    "xtask",
]

[workspace.dependencies]
once_cell = "1.18.0"
serde = { version = "1.0.100", features = ["derive"] }
syntect = { version = "5.1.0", default-features = false }

[package]
name = "two-face"
version = "0.3.0"
edition = "2021"
license = "MIT OR Apache-2.0"
rust-version = "1.64"
exclude = [
    "/.github/*",
    # We generate some large markdown files that are only linked by URL
    "/generated/*.md",
]
keywords = ["syntect", "extra", "syntaxes", "themes"]
description = "Extra syntax and theme definitions for syntect"
repository = "https://github.com/CosmicHorrorDev/two-face"
homepage = "https://github.com/CosmicHorrorDev/two-face"

[package.metadata.docs.rs]
all-features = true

[features]
# TODO: I don't like having to set this as a default, but `syntect` can't
#       compile without a regex impl
default = ["syntect-onig"]

syntect-onig = ["syntect/regex-onig"]
syntect-fancy = ["syntect/regex-fancy"]

# Don't like this, but I want to link to the functions provided by this from my
# documentation
unstable = ["syntect/default-syntaxes"]

[dependencies]
once_cell.workspace = true
serde.workspace = true

[dependencies.syntect]
workspace = true
features = ["dump-load", "parsing"]

[dev-dependencies]
strum = { version = "0.25.0", features = ["derive"] }
syntect = { workspace = true, features = ["html"] }
